### ISSUE TITLE
High executor thread consumption

### ISSUE THREAD

**Issue by ipalbeniz** [pivovarit/parallel-collectors#867] opened 2024-04-24 15:33 UTC
**Describe the bug**

Upon upgrading `parallel-collectors` from version **2.5.0** to **2.6.0**, we've observed an increase in thread consumption.
We are using a `org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor` with the following parameters: `corePoolSize` set to 1500, `maxPoolSize` set to 3000, and `queueCapacity` set to 100. 

While on version **2.5.0**, we never observed `corePoolSize` exceeding 1500.
However, upon upgrading to version **2.6.0**, `corePoolSize` increases from 1500 a few seconds after application startup. No other changes were made.

**To Reproduce**
I've prepared a unit test that functions correctly in the `2.5.0` tag but fails in the `2.6.0` tag and `master` branch:
```
@Test
void shouldExecuteParallelStreamsSequentially() {

    int tasks = 2;
    ThreadPoolExecutor myExecutor = new ThreadPoolExecutor(tasks,
                                                           tasks,
                                                           0L,
                                                           MILLISECONDS,
                                                           new LinkedBlockingQueue<>(tasks));

    Stream.of(210, 200, 160, 180)
        .collect(parallelToStream(i -> returnWithDelay(i, ofMillis(i)), myExecutor, tasks))
        .collect(toList());

    // 2.6.0 and master fail from here
    Stream.of(210, 200, 160, 180)
        .collect(parallelToStream(i -> returnWithDelay(i, ofMillis(i)), myExecutor, tasks))
        .collect(toList());
}
```

**Expected behavior**
I expect the unit test to pass in `master` branch and `2.6.0` tag.

Thank you in advance.

**Comment by pivovarit** [comment] 2024-04-24 16:47
Thanks for the reproducer, I managed to reproduce it locally. On it!

**Comment by pivovarit** [comment] 2024-04-25 08:20
I found the core issue - it's a side-effect of adjusting the architecture to be more virtual-thread-friendly. Unfortunately, it made it less platform-threads-friendly. I have a couple of ideas on how to tackle this, and you can expect the next release over the weekend

**Comment by ipalbeniz** [comment] 2024-04-25 09:14
I appreciate your time and effort in addressing it so quickly.
Thank you for your excellent work on this library!

**Comment by pivovarit** [comment] 2024-04-27 19:25
So, the reproducer that you provided is slightly flawed - the reason that the first stream works is by coincidence. You initialize an ExecutorService, and until you submit the first tasks, it's actually empty. 

The core issue is that all the tasks immediately hit the executor, and there's a short window of time in which two tasks are already in the queue, and the executor tries to offer the third one -> rejected execution!
 
So when you submit tasks for the first time, they actually bypass the working queue and get assigned to a newly created thread, so it's enough to warm up the executor first and then simply do:

```
@Test
void shouldExecuteParallelStreamsSequentially() {

    int tasks = 2;
    ThreadPoolExecutor myExecutor = new ThreadPoolExecutor(tasks,
      tasks,
      0L,
      MILLISECONDS,
      new LinkedBlockingQueue<>(tasks));

    for (int i = 0; i < tasks; i++) {
        CompletableFuture.runAsync(() -> {}, myExecutor).join();
    }

    Stream.of(210, 200, 160, 180)
      .collect(parallelToStream(i -> returnWithDelay(i, ofMillis(i)), myExecutor, tasks))
      .collect(toList());
}
```

I know that's a nice curiosity, but it does not really solve your problem. The problem is that if you have a stream with millions of elements and try to enforce max parallelism of two, **millions of tasks will still hit the executor**. I moved the limiting logic to the caller thread for streaming collectors (caller thread is not doing anything anyway, it can at least dispatch the tasks): https://github.com/pivovarit/parallel-collectors/pull/869

**Comment by pivovarit** [comment] 2024-04-29 05:45
I will also need to rethink what to do with collectors that return a future (something like https://github.com/pivovarit/parallel-collectors/pull/868), might take me a day or two

Also, just for the record, here's proof that tasks for new workers bypass the queue: https://github.com/openjdk/jdk/blob/4e5c25ee43d4ec31ed5160fd93a2fd15e35182f8/src/java.base/share/classes/java/util/concurrent/ThreadPoolExecutor.java#L1346-L1350

**Comment by pivovarit** [comment] 2024-05-01 07:27
Ok, the fix has been merged into the main branch. I will backport it today.

Here's a valid test case which passes on 2.5.0 and fails on 2.6.0:
```
package com.pivovarit.collectors.functional;

import com.pivovarit.collectors.ParallelCollectors;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import java.util.stream.Collector;
import java.util.stream.Stream;

import static java.util.stream.Collectors.toList;
import static java.util.stream.Stream.of;

class ExecutorPollutionTest {

    @TestFactory
    Stream<DynamicTest> shouldStartProcessingElementsTests() {
        return of(
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors::parallel, "parallel#1"),
          shouldNotSubmitMoreTasksThanParallelism((f, e, p) -> ParallelCollectors.parallel(f, toList(), e, p), "parallel#2"),
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors::parallelToStream, "parallelToStream"),
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors::parallelToOrderedStream, "parallelToOrderedStream"),
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors.Batching::parallel, "parallel#1 (batching)"),
          shouldNotSubmitMoreTasksThanParallelism((f, e, p) -> ParallelCollectors.Batching.parallel(f, toList(), e, p), "parallel#2 (batching)"),
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors.Batching::parallelToStream, "parallelToStream (batching)"),
          shouldNotSubmitMoreTasksThanParallelism(ParallelCollectors.Batching::parallelToOrderedStream, "parallelToOrderedStream (batching)")
        );
    }

    private static DynamicTest shouldNotSubmitMoreTasksThanParallelism(CollectorFactory<Integer> collector, String name) {
        return DynamicTest.dynamicTest(name, () -> {
            ExecutorService e = warmedUp(new ThreadPoolExecutor(2, 2, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>(2)));

            Object result = Stream.generate(() -> 42)
              .limit(1000)
              .collect(collector.apply(i -> i, e, 2));

            if (result instanceof CompletableFuture<?>) {
                ((CompletableFuture<?>) result).join();
            } else if (result instanceof Stream<?>) {
                ((Stream<?>) result).forEach((__) -> {});
            } else {
                throw new IllegalStateException("can't happen");
            }
        });
    }

    interface CollectorFactory<T> {
        Collector<T, ?, ?> apply(Function<T, ?> function, Executor executorService, int parallelism);
    }

    private static ThreadPoolExecutor warmedUp(ThreadPoolExecutor e) {
        for (int i = 0; i < e.getCorePoolSize(); i++) {
            e.submit(() -> {});
        }
        return e;
    }
}
```

**Comment by pivovarit** [comment] 2024-05-01 08:27
Here you go: https://github.com/pivovarit/parallel-collectors/releases/tag/2.6.1

I consider this fixed, if not, feel free to reopen :)

**Closed by pivovarit** 2024-05-01 08:27 UTC
Labels: bug
